name = "raymarch-dd"
entry = "src/main.dd"

[cxx]
standard = "c++20"

[include]
paths = ["/home/vega/Coding/GameDev/duduplayground/third_party/install/include"]

[pkg]
libs = ["sdl3"]
paths = ["/home/vega/Coding/GameDev/duduplayground/third_party/install/lib/pkgconfig"]

[build]
dir = "build"
